name: denki_bricks_helper
description: Helper methods shared between bricks
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  checked_yaml: ^2.0.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: any
  freezed: ^3.0.3
  json_serializable: ^6.9.4
  lints: ^6.0.0
