name: denki_service

environment:
  sdk: ^3.7.0

dependencies:
  mason: ^0.1.1
  denki_bricks_helper:
    git:
      url: https://github.com/denkilab-works/denki_bricks.git
      path: denki_service
      ref: main
# Uncomment this during development to quickly apply changes
# dependency_overrides:
#   denki_bricks_helper:
#     path: ../../denki_bricks_helper
